/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Record`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Dashboard` | `/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/DataContext` | `/DataContext`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Wallet` | `/Wallet`; params?: Router.UnknownInputParams; } | { pathname: `/Class/App`; params?: Router.UnknownInputParams; } | { pathname: `/Firebase/firebase`; params?: Router.UnknownInputParams; } | { pathname: `/Firebase/firebaseAuth`; params?: Router.UnknownInputParams; } | { pathname: `/Firebase/firebaseConfig`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/Record`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Dashboard` | `/Dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/DataContext` | `/DataContext`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Wallet` | `/Wallet`; params?: Router.UnknownOutputParams; } | { pathname: `/Class/App`; params?: Router.UnknownOutputParams; } | { pathname: `/Firebase/firebase`; params?: Router.UnknownOutputParams; } | { pathname: `/Firebase/firebaseAuth`; params?: Router.UnknownOutputParams; } | { pathname: `/Firebase/firebaseConfig`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/Record${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Dashboard${`?${string}` | `#${string}` | ''}` | `/Dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/DataContext${`?${string}` | `#${string}` | ''}` | `/DataContext${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Home${`?${string}` | `#${string}` | ''}` | `/Home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Wallet${`?${string}` | `#${string}` | ''}` | `/Wallet${`?${string}` | `#${string}` | ''}` | `/Class/App${`?${string}` | `#${string}` | ''}` | `/Firebase/firebase${`?${string}` | `#${string}` | ''}` | `/Firebase/firebaseAuth${`?${string}` | `#${string}` | ''}` | `/Firebase/firebaseConfig${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/Record`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Dashboard` | `/Dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/DataContext` | `/DataContext`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Home` | `/Home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Wallet` | `/Wallet`; params?: Router.UnknownInputParams; } | { pathname: `/Class/App`; params?: Router.UnknownInputParams; } | { pathname: `/Firebase/firebase`; params?: Router.UnknownInputParams; } | { pathname: `/Firebase/firebaseAuth`; params?: Router.UnknownInputParams; } | { pathname: `/Firebase/firebaseConfig`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
